# Generated by Django 5.2 on 2025-04-03 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectID', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('approve_amount', models.CharField(max_length=100)),
                ('requestable', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
