# Generated by Django 5.2 on 2025-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Budget_Code', models.CharField(max_length=20, unique=True)),
                ('Budget_Description', models.TextField()),
                ('Initial_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Revise_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'budget',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
