# Generated by Django 5.2 on 2025-04-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budget_delete_user'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Department_Code', models.CharField(max_length=20, unique=True)),
                ('Department_Name', models.TextField()),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Operation_Code', models.CharField(max_length=20, unique=True)),
                ('Operation_Description', models.TextField()),
                ('Total_Budget_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Currency', models.CharField(max_length=5)),
                ('Folder_Link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'operation_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperationBudget',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'operation_budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Project_Code', models.CharField(max_length=20, unique=True)),
                ('Project_Description', models.TextField()),
                ('Total_Budget_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Approved_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Currency', models.CharField(max_length=5)),
                ('Requestable', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('Folder_Link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'project_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'project_budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Trip_Code', models.CharField(max_length=20, unique=True)),
                ('Trip_Description', models.TextField()),
                ('Total_Budget_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Approved_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Currency', models.CharField(max_length=5)),
                ('Status', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
            ],
            options={
                'db_table': 'trip_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TripBudget',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'trip_budget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100, unique=True)),
                ('User_Email', models.CharField(max_length=100, unique=True)),
                ('Role', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Requester', models.CharField(max_length=100)),
                ('Request_No', models.CharField(max_length=50, unique=True)),
                ('Related_ID', models.PositiveIntegerField()),
                ('Flow_Type', models.CharField(choices=[('project', 'Project'), ('trip', 'Trip'), ('operation', 'Operation')], max_length=20)),
                ('Request_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Currency', models.CharField(max_length=10)),
                ('Content_Type', models.ForeignKey(limit_choices_to=models.Q(('model__in', ('project', 'trip', 'operation'))), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
