# Generated by Django 5.2 on 2025-04-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_department_operation_operationbudget_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancerequest',
            options={'managed': False},
        ),
    ]
