# Generated by Django 4.2 on 2025-04-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_advancerequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverSetupStep',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Step_No', models.IntegerField()),
                ('Maximum_Approval_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Approver_Email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'approver_setup_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Payment_No', models.CharField(max_length=20, unique=True)),
                ('Payment_Date', models.DateTimeField(auto_now_add=True)),
                ('Payment_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Currency', models.CharField(max_length=5)),
                ('Payment_Method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], max_length=20)),
                ('Payment_Note', models.TextField()),
                ('Received_Person', models.CharField(max_length=30)),
                ('Paid_Person', models.CharField(max_length=30)),
                ('Posting_Status', models.IntegerField(choices=[(1, 'Draft'), (0, 'Posted')])),
                ('Settlement_Status', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('Folder_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestSetUp',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Flow_Name', models.CharField(max_length=50)),
                ('Currency', models.CharField(max_length=5)),
                ('Flow_Type', models.CharField(choices=[('Project', 'Project'), ('Trip', 'Trip'), ('Operation', 'Operation')], max_length=50)),
                ('Description', models.TextField()),
                ('No_Of_Steps', models.IntegerField()),
                ('Management_Approver', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
            options={
                'db_table': 'request_setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('ID', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('Settlement_Date', models.DateTimeField(auto_now_add=True)),
                ('Settlement_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Currency', models.CharField(max_length=5)),
                ('Withdrawn_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Refund_Amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'settlement',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='projectbudget',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='advancerequest',
            table='advancerequest',
        ),
    ]
